### ISSUE TITLE
Error de salto de línea en los textos

### ISSUE THREAD

**Issue by SasurtioBackup** [TraduSquare/Steins-Gate-0-Traduccion-Esp#2]
Como dice el título me encontré con que los saltos de línea en los textos arrojan esos códigos en lugar del mero salto de línea. Me parece _(sigo sin confirmar)_ que es en todos los saltos de línea dentro de un mismo cajón de texto.

![image](https://user-images.githubusercontent.com/28857382/38534146-41054354-3c42-11e8-85b4-9f42a3f1f889.png)
![image](https://user-images.githubusercontent.com/28857382/38534189-7a7564ac-3c42-11e8-9da1-bd84e075b010.png)

**Comment by kronometro** [comment]
![sin titulo 2](https://user-images.githubusercontent.com/8495442/38574448-73912f64-3cbe-11e8-9aea-f2d1f9c3b947.jpg)
![sin titulo 4](https://user-images.githubusercontent.com/8495442/38574450-73d5a612-3cbe-11e8-8dc2-5a0269953521.jpg)
![sin titulo 5](https://user-images.githubusercontent.com/8495442/38574451-73fa1114-3cbe-11e8-8924-b6379fdb427c.jpg)
![sin titulo](https://user-images.githubusercontent.com/8495442/38574453-741fa866-3cbe-11e8-9147-902679137f9e.jpg)

**Comment by GateofSteiner-GoS** [comment]
Muchas gracias por el aviso, ya hemos sacado una actualización que lo arregla [,https://github.com/TraduSquare/Steins-Gate-0-Traduccion-Esp/releases/tag/FG1.1](https://github.com/TraduSquare/Steins-Gate-0-Traduccion-Esp/releases/tag/FG1.1) se nos habia pasado.
